/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Confirms the API is running. Doesn't touch the database.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Returns a bearer token valid for 12 hours (one shift). Deactivated staff are refused. After 5 failed attempts in 15 minutes the email is locked out with 429.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a password reset link
         * @description Always answers 202 so the response never reveals whether an account exists.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password using the emailed token
         * @description Reset tokens expire after 60 minutes and work once.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in staff member */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update your own name or phone number */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change your own password */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Terminals (depots) */
        get: operations["listTerminals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Customers and marketers
         * @description Also feeds the customer picker on Generate Ticket.
         */
        get: operations["listCustomers"];
        put?: never;
        /** Add a customer or marketer */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a customer or marketer */
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/api/loading-programs/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check an uploaded CSV without saving it
         * @description Returns how many rows are valid and a message for every row that isn't.
         */
        post: operations["previewLoadingProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loading-programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload the day's loading program
         * @description Saves every row as a program item. Refused with 422 if any row is invalid; row problems appear in `errors` keyed `rows.<row number>`.
         */
        post: operations["uploadLoadingProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/program-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trucks scheduled to load */
        get: operations["listProgramItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loading tickets */
        get: operations["listTickets"];
        put?: never;
        /**
         * Generate a loading ticket
         * @description Issues the next ticket number and puts the ticket in the Safety queue (`awaiting_safety`). Destination litres must add up to `requested_litres`, and `marketer` is required unless `truck_type` is `internal`.
         */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One ticket with its full history */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a ticket before Safety decides */
        patch: operations["updateTicket"];
        trace?: never;
    };
    "/api/tickets/{ticket_no}/inspection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve or reject a truck after the safety checklist
         * @description Only for tickets in `awaiting_safety`. Approval needs every toggle item checked; rejection needs `reason_code`. Notifies the Logistics officer who created the ticket.
         */
        post: operations["inspectTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_no}/loading-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record the litres actually loaded
         * @description Moves the ticket to `loaded`, or to `overload_pending` when the actual litres exceed the truck's capacity or the requested litres plus the overload tolerance. Admins are notified of overloads.
         */
        post: operations["recordLoading"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_no}/overload-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or deny an overloaded truck */
        post: operations["decideOverload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_no}/waybill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue the waybill for a loaded truck */
        post: operations["issueWaybill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_no}/gate-clearance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Let the truck leave the depot
         * @description Closes the ticket (`gate_cleared`).
         */
        post: operations["clearGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tickets waiting for inspection, longest wait first */
        get: operations["getSafetyQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The inspection checklist, in display order */
        get: operations["getSafetyChecklist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspection history */
        get: operations["listInspections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspections/{ticket_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The inspection of one ticket */
        get: operations["getInspection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dispatch/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trucks waiting at a dispatch stage
         * @description `loading` lists tickets approved by Safety; `waybill` lists loaded trucks; `gate` lists trucks with a waybill.
         */
        get: operations["getDispatchQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waybills/{waybill_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One waybill, for the printable page */
        get: operations["getWaybill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today's operations overview */
        get: operations["getDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trucks and litres per marketer */
        get: operations["getDashboardCharts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log of loading activity */
        get: operations["listAuditEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/{ticket_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything that happened to one ticket */
        get: operations["getAuditDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loaded trucks with litres requested and loaded */
        get: operations["getActivityReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/activity.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The same report as a CSV download */
        get: operations["exportActivityReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Staff records */
        get: operations["listStaff"];
        put?: never;
        /**
         * Create a staff profile
         * @description Issues the next staff number and emails the temporary password.
         */
        post: operations["createStaff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/next-number": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The staff number the next new profile will get */
        get: operations["getNextStaffNo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/{staff_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One staff profile */
        get: operations["getStaff"];
        put?: never;
        post?: never;
        /**
         * Delete a staff profile permanently
         * @description Refused with 409 when the staff member appears in ticket history; deactivate instead.
         */
        delete: operations["deleteStaff"];
        options?: never;
        head?: never;
        /** Edit a staff profile */
        patch: operations["updateStaff"];
        trace?: never;
    };
    "/api/staff/{staff_no}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Activate or deactivate a staff account
         * @description Deactivating signs the person out everywhere and blocks sign-in.
         */
        patch: operations["setStaffStatus"];
        trace?: never;
    };
    "/api/staff/{staff_no}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A staff member's profile picture
         * @description The image behind a user's `avatar_url`. Any signed-in staff member can load pictures, since they appear in the top bar and staff lists.
         */
        get: operations["getStaffAvatar"];
        put?: never;
        /** Upload a profile picture (JPEG, PNG or WebP, up to 2 MB) */
        post: operations["uploadStaffAvatar"];
        /** Remove the profile picture */
        delete: operations["deleteStaffAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your latest notifications */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark notifications as read */
        post: operations["markNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Support inbox */
        get: operations["listSupportRequests"];
        put?: never;
        /** Ask the admin team for help */
        post: operations["createSupportRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Resolve or reopen a support request */
        patch: operations["updateSupportRequest"];
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Depot configuration */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change depot configuration */
        patch: operations["updateSettings"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 24989001 */
        TicketNo: string;
        /** @example A1234567 */
        WaybillNo: string;
        /** @example BO001 */
        StaffNo: string;
        /**
         * @description Volume in litres.
         * @example 45000
         */
        Litres: number;
        /**
         * Format: date-time
         * @description ISO 8601 in UTC.
         * @example 2026-08-25T07:12:00Z
         */
        Timestamp: string;
        /** @enum {string} */
        Role: "admin" | "logistics" | "safety" | "dispatch";
        /** @enum {string} */
        TruckType: "internal" | "marketer" | "industrial";
        /** @enum {string} */
        Product: "PMS" | "AGO" | "DPK";
        /**
         * @description awaiting_safety → approved_for_loading | rejected; approved_for_loading → loaded | overload_pending; overload_pending → loaded | overload_denied; loaded → waybill_issued → gate_cleared.
         * @enum {string}
         */
        TicketStatus: "awaiting_safety" | "approved_for_loading" | "rejected" | "overload_pending" | "overload_denied" | "loaded" | "waybill_issued" | "gate_cleared";
        /**
         * @description pending = awaiting_safety, overload_pending; rejected = rejected, overload_denied; approved = every other status.
         * @enum {string}
         */
        TicketStatusGroup: "pending" | "approved" | "rejected";
        /**
         * @description completed = gate_cleared; failed = rejected or overload_denied; pending otherwise.
         * @enum {string}
         */
        AuditStatus: "completed" | "pending" | "failed";
        /** @enum {string} */
        InspectionResult: "approved" | "rejected";
        /** @enum {string} */
        RejectionReason: "ppe" | "fire_safety" | "mechanical" | "signage" | "other";
        /** @enum {string} */
        OverloadDecision: "approved" | "denied";
        /** @enum {string} */
        LoadingOutcome: "within_limit" | "overloaded";
        /** @enum {string} */
        DispatchStage: "loading" | "waybill" | "gate";
        /** @enum {string} */
        Period: "today" | "week" | "month" | "year";
        /** @enum {string} */
        TimelineEventType: "ticket_created" | "ticket_edited" | "safety_inspected" | "loading_recorded" | "overload_decided" | "waybill_issued" | "gate_cleared";
        /** @enum {string} */
        NotificationType: "ticket_approved" | "ticket_rejected" | "program_uploaded" | "overload_requested" | "overload_decided" | "waybill_issued" | "support_request";
        /** @enum {string} */
        SupportStatus: "open" | "resolved";
        Health: {
            /** @constant */
            status: "ok";
        };
        Message: {
            message: string;
        };
        Error: {
            /** @description Human-readable explanation of what went wrong. */
            message: string;
        };
        ValidationError: {
            message: string;
            /** @description Messages keyed by field path, e.g. `destinations.1.litres`. */
            errors: {
                [key: string]: string[];
            };
        };
        PaginationMeta: {
            page: number;
            per_page: number;
            /** @description Matching records across all pages. */
            total: number;
        };
        TerminalRef: {
            id: number;
            /** @example Terminal 1 */
            name: string;
        };
        Terminal: {
            id: number;
            name: string;
            address: string;
        };
        TerminalList: {
            data: components["schemas"]["Terminal"][];
        };
        TerminalInput: {
            /** @description Omit or null to add a terminal. */
            id?: number | null;
            name: string;
            address: string;
        };
        StaffRef: {
            staff_no: components["schemas"]["StaffNo"];
            name: string;
        };
        CustomerRef: {
            id: number;
            name: string;
            kind: components["schemas"]["TruckType"];
        };
        Customer: {
            id: number;
            name: string;
            kind: components["schemas"]["TruckType"];
            representative: string | null;
            phone: string | null;
            /** Format: email */
            email: string | null;
        };
        CustomerPage: {
            data: components["schemas"]["Customer"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CustomerInput: {
            name: string;
            kind: components["schemas"]["TruckType"];
            representative?: string | null;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
        };
        CustomerPatch: {
            name?: string;
            kind?: components["schemas"]["TruckType"];
            representative?: string | null;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
        };
        TruckRef: {
            /** @example BDJ580XB */
            plate: string;
            type: components["schemas"]["TruckType"];
        };
        Truck: {
            plate: string;
            type: components["schemas"]["TruckType"];
            capacity_litres: components["schemas"]["Litres"];
        };
        Driver: {
            name: string;
            phone: string;
        };
        Destination: {
            station: string;
            address: string;
            litres: components["schemas"]["Litres"];
        };
        MarketerContact: {
            name: string;
            representative: string;
            phone: string;
        };
        User: {
            staff_no: components["schemas"]["StaffNo"];
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            terminal: components["schemas"]["TerminalRef"];
            /** @example Safety */
            department: string;
            /** @description App access. Null for staff who don't sign in. */
            role: components["schemas"]["Role"] | null;
            /** @example Depot Manager */
            role_title: string;
            active: boolean;
            /** @description Path of `GET /api/staff/{staff_no}/avatar` with a version query that changes with each upload, e.g. `/api/staff/BO003/avatar?v=3f2a9c1e`. Null without a picture. */
            avatar_url: string | null;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            expires_at: components["schemas"]["Timestamp"];
            user: components["schemas"]["User"];
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            password: string;
            password_confirmation: string;
        };
        UpdateMeRequest: {
            name?: string;
            phone?: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            password: string;
            password_confirmation: string;
        };
        ProgramUpload: {
            /** @description CSV with columns customer, truck_plate, truck_type, product, quantity_litres, destination. Up to 1 MB. */
            file: string;
            /** Format: date */
            date: string;
            terminal_id: number;
        };
        ProgramImportError: {
            /** @description 1-based row number in the file, counting the header. */
            row: number;
            /** @example Unknown truck BDJ999XX. */
            message: string;
        };
        ProgramPreview: {
            valid_rows: number;
            errors: components["schemas"]["ProgramImportError"][];
        };
        LoadingProgram: {
            id: number;
            /** Format: date */
            date: string;
            terminal: components["schemas"]["TerminalRef"];
            uploaded_by: components["schemas"]["StaffRef"];
            item_count: number;
            uploaded_at: components["schemas"]["Timestamp"];
        };
        ProgramItem: {
            id: number;
            program_id: number;
            /** Format: date */
            date: string;
            customer: components["schemas"]["CustomerRef"];
            truck: components["schemas"]["TruckRef"];
            product: components["schemas"]["Product"];
            quantity_litres: components["schemas"]["Litres"];
            destination: string;
            /** @description The ticket generated from this item, once there is one. */
            ticket_no: components["schemas"]["TicketNo"] | null;
        };
        ProgramItemPage: {
            data: components["schemas"]["ProgramItem"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        Ticket: {
            ticket_no: components["schemas"]["TicketNo"];
            terminal: components["schemas"]["TerminalRef"];
            customer: components["schemas"]["CustomerRef"];
            truck: components["schemas"]["TruckRef"];
            product: components["schemas"]["Product"];
            requested_litres: components["schemas"]["Litres"];
            /** @example Akobo 4 (30,000L) / Akobo 3 (15,000L) */
            destination_summary: string;
            status: components["schemas"]["TicketStatus"];
            created_at: components["schemas"]["Timestamp"];
        };
        TicketPage: {
            data: components["schemas"]["Ticket"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        InspectionOutcome: {
            result: components["schemas"]["InspectionResult"];
            reason_code: components["schemas"]["RejectionReason"] | null;
            notes: string | null;
            inspector: components["schemas"]["StaffRef"];
            inspected_at: components["schemas"]["Timestamp"];
        };
        LoadingRecord: {
            actual_litres: components["schemas"]["Litres"];
            /** @description Actual minus requested; negative when under-loaded. */
            variance_litres: number;
            outcome: components["schemas"]["LoadingOutcome"];
            loader: components["schemas"]["StaffRef"];
            recorded_at: components["schemas"]["Timestamp"];
        };
        WaybillRef: {
            waybill_no: components["schemas"]["WaybillNo"];
            issued_at: components["schemas"]["Timestamp"];
        };
        TicketDetail: components["schemas"]["Ticket"] & {
            destinations: components["schemas"]["Destination"][];
            /** @description Null for internal trucks. */
            marketer: components["schemas"]["MarketerContact"] | null;
            driver: components["schemas"]["Driver"] | null;
            created_by: components["schemas"]["StaffRef"];
            inspection: components["schemas"]["InspectionOutcome"] | null;
            loading: components["schemas"]["LoadingRecord"] | null;
            waybill: components["schemas"]["WaybillRef"] | null;
            gate_cleared_at: components["schemas"]["Timestamp"] | null;
        };
        TicketInput: {
            /** @description The loading program row this ticket was started from. */
            program_item_id?: number | null;
            terminal_id: number;
            customer_id: number;
            truck_plate: string;
            truck_type: components["schemas"]["TruckType"];
            product: components["schemas"]["Product"];
            requested_litres: number;
            driver?: components["schemas"]["Driver"] | null;
            destinations: components["schemas"]["Destination"][];
            marketer?: components["schemas"]["MarketerContact"] | null;
        };
        TicketPatch: {
            terminal_id?: number;
            truck_plate?: string;
            truck_type?: components["schemas"]["TruckType"];
            product?: components["schemas"]["Product"];
            requested_litres?: number;
            driver?: components["schemas"]["Driver"] | null;
            destinations?: components["schemas"]["Destination"][];
            marketer?: components["schemas"]["MarketerContact"] | null;
        };
        QueueTicket: {
            ticket_no: components["schemas"]["TicketNo"];
            customer: components["schemas"]["CustomerRef"];
            truck: components["schemas"]["TruckRef"];
            product: components["schemas"]["Product"];
            requested_litres: components["schemas"]["Litres"];
            driver: components["schemas"]["Driver"] | null;
            waiting_minutes: number;
        };
        QueueTicketList: {
            data: components["schemas"]["QueueTicket"][];
            meta: {
                total: number;
            };
        };
        ChecklistItem: {
            /** @example fire_extinguisher */
            key: string;
            /** @example Fire Extinguisher */
            label: string;
            section_no: number;
            /** @example Fire & Static Prevention */
            section_title: string;
            /**
             * @description toggle = present or not; count = a number from 0 to `max`.
             * @enum {string}
             */
            input: "toggle" | "count";
            max?: number;
        };
        ChecklistItemList: {
            data: components["schemas"]["ChecklistItem"][];
        };
        InspectionInput: {
            result: components["schemas"]["InspectionResult"];
            /** @description Checklist answers keyed by item key — true/false for toggles, a number for counts. */
            checks: {
                [key: string]: boolean | number;
            };
            reason_code?: components["schemas"]["RejectionReason"] | null;
            notes?: string | null;
        };
        Inspection: {
            ticket_no: components["schemas"]["TicketNo"];
            terminal: components["schemas"]["TerminalRef"];
            customer: components["schemas"]["CustomerRef"];
            truck: components["schemas"]["TruckRef"];
            driver: components["schemas"]["Driver"] | null;
            result: components["schemas"]["InspectionResult"];
            reason_code: components["schemas"]["RejectionReason"] | null;
            notes: string | null;
            inspector: components["schemas"]["StaffRef"];
            inspected_at: components["schemas"]["Timestamp"];
        };
        InspectionSummary: {
            inspected: number;
            approved: number;
            rejected: number;
            generated_at: components["schemas"]["Timestamp"];
        };
        InspectionPage: {
            data: components["schemas"]["Inspection"][];
            meta: components["schemas"]["PaginationMeta"] & {
                summary: components["schemas"]["InspectionSummary"];
            };
        };
        DispatchQueueItem: {
            ticket_no: components["schemas"]["TicketNo"];
            stage: components["schemas"]["DispatchStage"];
            customer: components["schemas"]["CustomerRef"];
            truck: components["schemas"]["Truck"];
            product: components["schemas"]["Product"];
            requested_litres: components["schemas"]["Litres"];
            waiting_minutes: number;
        };
        DispatchQueueList: {
            data: components["schemas"]["DispatchQueueItem"][];
            meta: {
                total: number;
                /**
                 * @description The current overload tolerance, so Dispatch can preview a load's outcome.
                 * @example 1
                 */
                overload_tolerance_percent: number;
            };
        };
        LoadingRecordInput: {
            actual_litres: number;
        };
        OverloadDecisionInput: {
            decision: components["schemas"]["OverloadDecision"];
            note?: string | null;
        };
        Waybill: {
            waybill_no: components["schemas"]["WaybillNo"];
            ticket_no: components["schemas"]["TicketNo"];
            issued_at: components["schemas"]["Timestamp"];
            dispatcher: components["schemas"]["StaffRef"];
            terminal: components["schemas"]["TerminalRef"];
            customer: components["schemas"]["CustomerRef"];
            truck: components["schemas"]["Truck"];
            driver: components["schemas"]["Driver"] | null;
            product: components["schemas"]["Product"];
            actual_litres: components["schemas"]["Litres"];
            destinations: components["schemas"]["Destination"][];
        };
        GateClearance: {
            ticket_no: components["schemas"]["TicketNo"];
            cleared_by: components["schemas"]["StaffRef"];
            cleared_at: components["schemas"]["Timestamp"];
        };
        DashboardStats: {
            generated_tickets: number;
            pending_tickets: number;
            approved_for_loading: number;
            trucks_dispatched: number;
            /** @description When the most recent ticket was generated today. */
            last_generated_at: components["schemas"]["Timestamp"] | null;
        };
        ChartPoint: {
            /** @example FATGBEMS */
            label: string;
            value: number;
        };
        DashboardCharts: {
            trucks_per_marketer: components["schemas"]["ChartPoint"][];
            /** @description Values in thousands of litres. */
            quantity_per_marketer: components["schemas"]["ChartPoint"][];
        };
        AuditEntry: {
            ticket_no: components["schemas"]["TicketNo"];
            /** Format: date */
            date: string;
            customer: components["schemas"]["CustomerRef"];
            truck: components["schemas"]["TruckRef"];
            product: components["schemas"]["Product"];
            requested_litres: components["schemas"]["Litres"];
            destination_summary: string;
            status: components["schemas"]["AuditStatus"];
        };
        AuditEntryPage: {
            data: components["schemas"]["AuditEntry"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        TimelineEntry: {
            event: components["schemas"]["TimelineEventType"];
            /** @example Loading Ticket Created */
            label: string;
            at: components["schemas"]["Timestamp"];
        };
        StaffOnDuty: {
            /** @example Safety */
            role_label: string;
            name: string;
        };
        LoadingSummary: {
            requested_litres: components["schemas"]["Litres"];
            actual_litres: components["schemas"]["Litres"];
            variance_litres: number;
            outcome: components["schemas"]["LoadingOutcome"];
        };
        AuditDetail: {
            ticket_no: components["schemas"]["TicketNo"];
            /** Format: date */
            date: string;
            terminal: components["schemas"]["TerminalRef"];
            status: components["schemas"]["AuditStatus"];
            /** @description Why the ticket failed or is still pending. */
            reason: string | null;
            truck: components["schemas"]["Truck"];
            product: components["schemas"]["Product"];
            loading_summary: components["schemas"]["LoadingSummary"] | null;
            waybill_no: components["schemas"]["WaybillNo"] | null;
            timeline: components["schemas"]["TimelineEntry"][];
            staff_on_duty: components["schemas"]["StaffOnDuty"][];
            overload_approved_by: components["schemas"]["StaffRef"] | null;
        };
        ActivityReportRow: {
            ticket_no: components["schemas"]["TicketNo"];
            waybill_no: components["schemas"]["WaybillNo"] | null;
            customer: components["schemas"]["CustomerRef"];
            truck: components["schemas"]["TruckRef"];
            product: components["schemas"]["Product"];
            requested_litres: components["schemas"]["Litres"];
            loaded_litres: components["schemas"]["Litres"] | null;
        };
        ActivityTotals: {
            requested_litres: components["schemas"]["Litres"];
            loaded_litres: components["schemas"]["Litres"];
            variance_litres: number;
        };
        ActivityReportPage: {
            data: components["schemas"]["ActivityReportRow"][];
            meta: components["schemas"]["PaginationMeta"] & {
                totals: components["schemas"]["ActivityTotals"];
                generated_at: components["schemas"]["Timestamp"];
            };
        };
        StaffPage: {
            data: components["schemas"]["User"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        StaffInput: {
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            terminal_id: number;
            department: string;
            role: components["schemas"]["Role"] | null;
            role_title: string;
            temporary_password: string;
        };
        StaffPatch: {
            name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            terminal_id?: number;
            department?: string;
            role?: components["schemas"]["Role"] | null;
            role_title?: string;
        };
        StaffStatusInput: {
            active: boolean;
        };
        NextStaffNo: {
            staff_no: components["schemas"]["StaffNo"];
        };
        AvatarUpload: {
            file: string;
        };
        Notification: {
            id: number;
            type: components["schemas"]["NotificationType"];
            /** @example Loading ticket #24989001 was approved by Safety. */
            title: string;
            ticket_no: components["schemas"]["TicketNo"] | null;
            created_at: components["schemas"]["Timestamp"];
            read_at: components["schemas"]["Timestamp"] | null;
        };
        NotificationList: {
            data: components["schemas"]["Notification"][];
            meta: {
                unread: number;
            };
        };
        MarkNotificationsReadInput: {
            /** @description Notifications to mark; null marks all of yours. */
            ids: number[] | null;
        };
        SupportRequest: {
            id: number;
            subject: string;
            body: string;
            status: components["schemas"]["SupportStatus"];
            requester: components["schemas"]["StaffRef"];
            created_at: components["schemas"]["Timestamp"];
        };
        SupportRequestPage: {
            data: components["schemas"]["SupportRequest"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        SupportRequestInput: {
            subject: string;
            body: string;
        };
        SupportRequestPatch: {
            status: components["schemas"]["SupportStatus"];
        };
        Settings: {
            terminals: components["schemas"]["Terminal"][];
            products: components["schemas"]["Product"][];
            checklist: components["schemas"]["ChecklistItem"][];
            /**
             * @description How far above the requested litres a load may go before it counts as overloaded.
             * @example 1
             */
            overload_tolerance_percent: number;
        };
        SettingsPatch: {
            terminals?: components["schemas"]["TerminalInput"][];
            checklist?: components["schemas"]["ChecklistItem"][];
            overload_tolerance_percent?: number;
        };
    };
    responses: {
        /** @description Missing, expired or revoked token. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The signed-in role can't call this endpoint. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No record matches the URL. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The ticket isn't at the workflow stage this action needs. */
        WrongStage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description One or more fields are invalid. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationError"];
            };
        };
        /** @description Too many attempts; try again later. */
        TooManyAttempts: {
            headers: {
                /** @description Seconds until another attempt is allowed. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Page: number;
        PerPage: number;
        /** @description Free-text search across the list's text columns. */
        Search: string;
        /** @description Time window counted in Lagos time. Ignored when `year` is set. */
        Period: components["schemas"]["Period"];
        /** @description Archive year, e.g. 2025. Overrides `period`. */
        Year: number;
        TruckTypeFilter: components["schemas"]["TruckType"];
        TicketNoPath: components["schemas"]["TicketNo"];
        WaybillNoPath: components["schemas"]["WaybillNo"];
        StaffNoPath: components["schemas"]["StaffNo"];
        CustomerIdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Email or password is incorrect, or the account is deactivated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The staff member has no app access (no role). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyAttempts"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description A reset link was sent if the account exists. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyAttempts"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed. Existing tokens for the account are revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed. Other sessions are signed out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listTerminals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All terminals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listCustomers: {
        parameters: {
            query?: {
                /** @description Free-text search across the list's text columns. */
                q?: components["parameters"]["Search"];
                kind?: components["schemas"]["TruckType"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of customers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CustomerIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerPatch"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    previewLoadingProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ProgramUpload"];
            };
        };
        responses: {
            /** @description Validation report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramPreview"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    uploadLoadingProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ProgramUpload"];
            };
        };
        responses: {
            /** @description Program saved. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadingProgram"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listProgramItems: {
        parameters: {
            query?: {
                /** @description Program date in Lagos time. Defaults to today. */
                date?: string;
                truck_type?: components["parameters"]["TruckTypeFilter"];
                /** @description Free-text search across the list's text columns. */
                q?: components["parameters"]["Search"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of program items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramItemPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listTickets: {
        parameters: {
            query?: {
                status_group?: components["schemas"]["TicketStatusGroup"];
                /** @description One exact workflow status, e.g. `overload_pending` for the admin's overload approvals. */
                status?: components["schemas"]["TicketStatus"];
                truck_type?: components["parameters"]["TruckTypeFilter"];
                /** @description Time window counted in Lagos time. Ignored when `year` is set. */
                period?: components["parameters"]["Period"];
                /** @description Archive year, e.g. 2025. Overrides `period`. */
                year?: components["parameters"]["Year"];
                /** @description Free-text search across the list's text columns. */
                q?: components["parameters"]["Search"];
                /** @description Prefix with `-` for descending. */
                sort?: "created_at" | "-created_at" | "customer" | "-customer" | "requested_litres" | "-requested_litres";
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of tickets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketInput"];
            };
        };
        responses: {
            /** @description Ticket created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_no: components["parameters"]["TicketNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_no: components["parameters"]["TicketNoPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketPatch"];
            };
        };
        responses: {
            /** @description Updated ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["WrongStage"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    inspectTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_no: components["parameters"]["TicketNoPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspectionInput"];
            };
        };
        responses: {
            /** @description Inspection recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inspection"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["WrongStage"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    recordLoading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_no: components["parameters"]["TicketNoPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadingRecordInput"];
            };
        };
        responses: {
            /** @description Loading recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["WrongStage"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    decideOverload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_no: components["parameters"]["TicketNoPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverloadDecisionInput"];
            };
        };
        responses: {
            /** @description Decision recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["WrongStage"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    issueWaybill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_no: components["parameters"]["TicketNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Waybill issued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Waybill"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["WrongStage"];
        };
    };
    clearGate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_no: components["parameters"]["TicketNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gate cleared. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateClearance"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["WrongStage"];
        };
    };
    getSafetyQueue: {
        parameters: {
            query?: {
                truck_type?: components["parameters"]["TruckTypeFilter"];
                /** @description Free-text search across the list's text columns. */
                q?: components["parameters"]["Search"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The queue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueTicketList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getSafetyChecklist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checklist items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItemList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listInspections: {
        parameters: {
            query?: {
                result?: components["schemas"]["InspectionResult"];
                /** @description Time window counted in Lagos time. Ignored when `year` is set. */
                period?: components["parameters"]["Period"];
                /** @description Archive year, e.g. 2025. Overrides `period`. */
                year?: components["parameters"]["Year"];
                /** @description Free-text search across the list's text columns. */
                q?: components["parameters"]["Search"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of inspections with totals for the period. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getInspection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_no: components["parameters"]["TicketNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The inspection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inspection"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getDispatchQueue: {
        parameters: {
            query: {
                stage: components["schemas"]["DispatchStage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The queue for that stage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchQueueList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getWaybill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waybill_no: components["parameters"]["WaybillNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The waybill. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Waybill"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getDashboardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Counts for today, in Lagos time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getDashboardCharts: {
        parameters: {
            query?: {
                product?: components["schemas"]["Product"];
                /** @description Time window counted in Lagos time. Ignored when `year` is set. */
                period?: components["parameters"]["Period"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chart series. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardCharts"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAuditEntries: {
        parameters: {
            query?: {
                truck_type?: components["parameters"]["TruckTypeFilter"];
                /** @description Time window counted in Lagos time. Ignored when `year` is set. */
                period?: components["parameters"]["Period"];
                /** @description Archive year, e.g. 2025. Overrides `period`. */
                year?: components["parameters"]["Year"];
                /** @description Free-text search across the list's text columns. */
                q?: components["parameters"]["Search"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAuditDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_no: components["parameters"]["TicketNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The audit detail, built from recorded events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getActivityReport: {
        parameters: {
            query?: {
                truck_type?: components["parameters"]["TruckTypeFilter"];
                /** @description Time window counted in Lagos time. Ignored when `year` is set. */
                period?: components["parameters"]["Period"];
                /** @description Archive year, e.g. 2025. Overrides `period`. */
                year?: components["parameters"]["Year"];
                /** @description Free-text search across the list's text columns. */
                q?: components["parameters"]["Search"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of rows with totals for the whole period. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityReportPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportActivityReport: {
        parameters: {
            query?: {
                truck_type?: components["parameters"]["TruckTypeFilter"];
                /** @description Time window counted in Lagos time. Ignored when `year` is set. */
                period?: components["parameters"]["Period"];
                /** @description Archive year, e.g. 2025. Overrides `period`. */
                year?: components["parameters"]["Year"];
                /** @description Free-text search across the list's text columns. */
                q?: components["parameters"]["Search"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file, streamed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listStaff: {
        parameters: {
            query?: {
                /** @description Free-text search across the list's text columns. */
                q?: components["parameters"]["Search"];
                department?: string;
                active?: boolean;
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of staff. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createStaff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getNextStaffNo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The next staff number. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextStaffNo"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_no: components["parameters"]["StaffNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_no: components["parameters"]["StaffNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The staff member appears in ticket history. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_no: components["parameters"]["StaffNoPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffPatch"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    setStaffStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_no: components["parameters"]["StaffNoPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffStatusInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getStaffAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_no: components["parameters"]["StaffNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The picture. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadStaffAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_no: components["parameters"]["StaffNoPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AvatarUpload"];
            };
        };
        responses: {
            /** @description Updated profile with the new picture. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteStaffAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_no: components["parameters"]["StaffNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated profile without a picture. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                /** @description Only unread notifications. */
                unread?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 50 notifications, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    markNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkNotificationsReadInput"];
            };
        };
        responses: {
            /** @description Marked as read. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listSupportRequests: {
        parameters: {
            query?: {
                status?: components["schemas"]["SupportStatus"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of support requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportRequestPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createSupportRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupportRequestInput"];
            };
        };
        responses: {
            /** @description Request sent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportRequest"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    updateSupportRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupportRequestPatch"];
            };
        };
        responses: {
            /** @description The updated request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportRequest"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
}
