"use client";

import { useState, useEffect, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { TicketPreviewPanel, type TicketPreviewData } from "./ticket-preview-panel";

interface Destination {
  station: string;
  quantity: string;
  address: string;
}

interface LoadingProgramFormProps {
  initial?: {
    truckType?: string;
    truckNumber?: string;
    product?: string;
    quantity?: string;
  };
}

const TERMINALS = ["Terminal 1", "Terminal 2"];
const TRUCK_TYPES = ["Internal", "Marketer", "External"];
const PRODUCTS = ["PMS", "AGO (Diesel)", "DPK"];

const selectClass =
  "flex h-14 w-full rounded-xl border border-input bg-surface px-3.5 text-sm text-foreground transition-colors focus-visible:border-ring focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40";

function normalizeTruckType(value?: string) {
  if (value === "Industrial") return "External";
  return value && TRUCK_TYPES.includes(value) ? value : TRUCK_TYPES[0];
}

function normalizeProduct(value?: string) {
  if (!value) return PRODUCTS[0];
  if (value.includes("AGO") || value.includes("Diesel")) return "AGO (Diesel)";
  if (value.includes("DPK")) return "DPK";
  return "PMS";
}

function formatQuantity(value?: string) {
  if (!value) return "33,000 Litres";
  const amount = Number(value);
  return Number.isFinite(amount) && amount > 0
    ? `${amount.toLocaleString("en-US")} Litres`
    : value;
}

export function LoadingProgramForm({ initial }: LoadingProgramFormProps) {
  const router = useRouter();

  const [ticketId, setTicketId] = useState("00234567");
  const [date, setDate] = useState("");
  const [time, setTime] = useState("");
  const [terminal, setTerminal] = useState(TERMINALS[0]);
  const [truckType, setTruckType] = useState(() =>
    normalizeTruckType(initial?.truckType),
  );
  const [truckNumber, setTruckNumber] = useState(
    initial?.truckNumber ?? "BDJ580XB",
  );
  const [requestedAmount, setRequestedAmount] = useState(() =>
    formatQuantity(initial?.quantity),
  );
  const [product, setProduct] = useState(() =>
    normalizeProduct(initial?.product),
  );
  const [destinations, setDestinations] = useState<Destination[]>([
    {
      station: "Babatunde Ishola Filling Station",
      quantity: formatQuantity(initial?.quantity),
      address: "51, Apapa-Oshodi Expressway, Ijeshatedo, Lagos",
    },
  ]);
  const [marketer, setMarketer] = useState("");
  const [representative, setRepresentative] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [isPreview, setIsPreview] = useState(false);

  // Date & time are auto-generated by the system, not user-editable.
  useEffect(() => {
    const now = new Date();
    setDate(
      now.toLocaleDateString("en-US", {
        weekday: "short",
        day: "numeric",
        month: "short",
        year: "numeric",
      }),
    );
    setTime(
      now.toLocaleTimeString("en-US", {
        hour: "2-digit",
        minute: "2-digit",
        hour12: false,
      }),
    );
  }, []);

  const requiresMarketer = truckType !== "Internal";

  function handleAddDestination() {
    setDestinations((current) => [
      ...current,
      { station: "", quantity: "", address: "" },
    ]);
  }

  function handleRemoveDestination(index: number) {
    setDestinations((current) => current.filter((_, i) => i !== index));
  }

  function handleDestinationChange(
    index: number,
    field: keyof Destination,
    value: string,
  ) {
    setDestinations((current) =>
      current.map((destination, i) =>
        i === index ? { ...destination, [field]: value } : destination,
      ),
    );
  }

  const previewData: TicketPreviewData = {
    ticketId,
    date,
    time,
    depot: terminal,
    truckType,
    truckNumber,
    product,
    requestedAmount,
    destinations,
    marketer,
    representative,
    phoneNumber,
  };

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setIsPreview(true);
  }

  if (isPreview) {
    return (
      <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <TicketPreviewPanel
          ticket={previewData}
          onEdit={() => setIsPreview(false)}
          onCreate={() => router.push("/ticket-history")}
        />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="text-sm font-medium text-muted-foreground">
              Loading Ticket
            </p>
            <h1 className="text-3xl font-bold tracking-tight text-foreground">
              Generate Loading Ticket
            </h1>
          </div>
          <div className="flex flex-col gap-3 sm:flex-row">
            <Button
              variant="secondary"
              type="button"
              onClick={() => router.push("/loading-program")}
            >
              Cancel
            </Button>
            <Button type="submit">Preview Ticket</Button>
          </div>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Basic Info</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="ticket-id">Ticket ID</Label>
              <Input
                id="ticket-id"
                name="ticketId"
                value={ticketId}
                onChange={(event) => setTicketId(event.target.value)}
                className="h-14 rounded-xl"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="date">Date</Label>
              <Input
                id="date"
                name="date"
                value={date}
                readOnly
                aria-readonly
                className="h-14 rounded-xl bg-muted/50 text-muted-foreground"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="time">Time</Label>
              <Input
                id="time"
                name="time"
                value={time}
                readOnly
                aria-readonly
                className="h-14 rounded-xl bg-muted/50 text-muted-foreground"
              />
            </div>
            <div className="space-y-2 sm:col-span-2">
              <Label htmlFor="terminal">Terminal</Label>
              <select
                id="terminal"
                name="terminal"
                value={terminal}
                onChange={(event) => setTerminal(event.target.value)}
                className={selectClass}
              >
                {TERMINALS.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>
            <p className="text-xs text-muted-foreground sm:col-span-3">
              Date and time are generated automatically when the ticket is
              created.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Truck Info</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="truck-type">Truck Type</Label>
              <select
                id="truck-type"
                name="truckType"
                value={truckType}
                onChange={(event) => setTruckType(event.target.value)}
                className={selectClass}
              >
                {TRUCK_TYPES.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="truck-number">Truck Number</Label>
              <Input
                id="truck-number"
                name="truckNumber"
                value={truckNumber}
                onChange={(event) => setTruckNumber(event.target.value)}
                className="h-14 rounded-xl"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="requested-amount">Requested Loading Amount</Label>
              <Input
                id="requested-amount"
                name="requestedAmount"
                value={requestedAmount}
                onChange={(event) => setRequestedAmount(event.target.value)}
                className="h-14 rounded-xl"
              />
            </div>
            <div className="space-y-2 sm:col-span-3">
              <Label htmlFor="product">Product</Label>
              <select
                id="product"
                name="product"
                value={product}
                onChange={(event) => setProduct(event.target.value)}
                className={selectClass}
              >
                {PRODUCTS.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Destination / Distribution</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            {destinations.map((destination, index) => (
              <div
                key={index}
                className="rounded-2xl border border-border bg-surface p-5"
              >
                <div className="mb-4 flex items-center justify-between gap-4">
                  <p className="text-sm font-semibold text-foreground">
                    Destination {index + 1}
                  </p>
                  {destinations.length > 1 && (
                    <Button
                      variant="outline"
                      type="button"
                      onClick={() => handleRemoveDestination(index)}
                      className="h-10 px-3 text-sm"
                    >
                      <Trash2 className="size-4" />
                    </Button>
                  )}
                </div>
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor={`station-${index}`}>Station</Label>
                    <Input
                      id={`station-${index}`}
                      value={destination.station}
                      onChange={(event) =>
                        handleDestinationChange(
                          index,
                          "station",
                          event.target.value,
                        )
                      }
                      className="h-14 rounded-xl"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor={`quantity-${index}`}>
                      Quantity to be Discharged
                    </Label>
                    <Input
                      id={`quantity-${index}`}
                      value={destination.quantity}
                      onChange={(event) =>
                        handleDestinationChange(
                          index,
                          "quantity",
                          event.target.value,
                        )
                      }
                      className="h-14 rounded-xl"
                    />
                  </div>
                </div>
                <div className="mt-4 space-y-2">
                  <Label htmlFor={`address-${index}`}>Address</Label>
                  <Input
                    id={`address-${index}`}
                    value={destination.address}
                    onChange={(event) =>
                      handleDestinationChange(
                        index,
                        "address",
                        event.target.value,
                      )
                    }
                    className="h-14 rounded-xl"
                  />
                </div>
              </div>
            ))}

            <Button
              type="button"
              variant="outline"
              className="inline-flex items-center gap-2"
              onClick={handleAddDestination}
            >
              <Plus className="size-4" />
              Add another destination
            </Button>
          </CardContent>
        </Card>

        {requiresMarketer && (
          <Card>
            <CardHeader>
              <CardTitle>Marketer Information</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4 sm:grid-cols-3">
              <div className="space-y-2">
                <Label htmlFor="marketer">Marketer</Label>
                <Input
                  id="marketer"
                  value={marketer}
                  onChange={(event) => setMarketer(event.target.value)}
                  placeholder="Enter marketer"
                  className="h-14 rounded-xl"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="representative">Representative</Label>
                <Input
                  id="representative"
                  value={representative}
                  onChange={(event) => setRepresentative(event.target.value)}
                  placeholder="Enter representative"
                  className="h-14 rounded-xl"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="phone">Phone Number</Label>
                <Input
                  id="phone"
                  value={phoneNumber}
                  onChange={(event) => setPhoneNumber(event.target.value)}
                  placeholder="Enter phone number"
                  className="h-14 rounded-xl"
                />
              </div>
            </CardContent>
          </Card>
        )}
      </form>
    </div>
  );
}
